trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: '/dist/reddit-up'
    env:
      azure_static_web_apps_api_token: $(deployment_token)